# tips

[参考文献1](https://www.bilibili.com/video/BV1Wy4y1h7ii/?spm_id_from=333.1007.top_right_bar_window_history.content.click)

* 笔记中大写字母为矩阵，小写字母为数字（变量）
* numpy所有的运算都是围绕着数组进行的，因此在计算前我们需要将所有的数据表示成数组的形式（也可以理解为向量化）,numpy的核心就是将问题向量化，并行化这种思路
* numpy中默认的数据类型是float64(64的浮点数)，可以在创建数组时用参数dtype=np.int32来指定数据类型，例如：np.zeros((3,2),dtype=int32)
* 可用的数据类型：整形：int64/32/16/8;无符号整形：uint8/16/32/64;浮点数：float64/32;布尔值：bool;字符串：str...
* Python的一个列表里面可以存储多种类型的数据，而np.array()只能存储一种类型的数组，即要么全是float64 要么全是int，不能既有float64又有int；这也是np快的原因之一
* 关于切片 -slice（索引，筛选），其标准样式为a[x:y:n]（一维），由两个引号分离开形成三个空间，第一个空间为起始位置，第二个空间为结束位置,第三个空间为步长;二维则是a[x1:y1:n1,x2:y2:n2]和维度的看法是一样的，即第一位是最高维，由高维向低维排列；
* Python的切片是按照其索引位置进行切片的，索引是一定的，是不会改变的，是从0开始的
* Python的切片一般都是取前不取后（步长为正），即[a,b)前闭后开的区间，其在步长为一的情况下，总共的元素个数为(b-a), 若步长大于1则含有的个数为[(b-a)/n],其中a为初始点，b为终点，n为步长，[]是取整符号 --[x]是指不超过x的最大整数；当步长为负的时候则是指，从最后一个数往前取数，取还是可以沿用步长为正的思路，例如：a[4:2:-1]是指从索引为4的那个数的位置开始根据步长为1往前取数，同样也是取前不取后，即取a[4],a[3]这两数，不取a[2];取数的个数为$[\frac{|(a-b)|}{n}]$,其发生变化的是将（a-b）添加了绝对值
* 关于对切片的解读a[a:b],解读为从a开始到(b-1)结束
* 指定某些行与某些列的切片方法a[[1,3,4],[4,5,8]]
* 假如我们想slicing第n行到第m行，则我们检索的写法为a[n,m+1],(m+1)-n 是我们能得到的真是行数;逆向来说我们需要从第n列开始到结束一共k列，其取法为a[n,n+(k+1)]
* 关于索引掩码[快速抵达](https://www.bilibili.com/video/BV1xK411X7ZQ?t=844.4)
* "a<n"会返回一个索引掩码，[True,True,False,False,True],然后索引掩码再带入a中，即a[np.array([True,True,False,False,True])],则只返回为True的对应位置的元素，即返回含三个元素的数组[a[0],a[1],a[4]]  
* 关于轴与维度，轴axis = n，这个n就是那个对应数组.shape 元组对应下标（索引）的那个维度；例如：a.shape ==>(4,3,6,5) axis=0 就是"4"而"4"所在的维度为四维所以axis=0，就是指的第四维  

网友的总结[参考文献1](https://www.bilibili.com/video/BV1Wy4y1h7ii/?spm_id_from=333.1007.top_right_bar_window_history.content.click)：  
18.a.mean() 返回数组的平均值  
19.np.median(a) 返回数组的中位数  
20.a.var() 返回方差  
21. a.std() 标准差  
22. a.sum(axis = 1)    
a.sum(axis = 0)  
23.a[0,1] 取下标 0 1 的元素  
24. a[ (a > 3) & (a % 2 == 0) ] 取大于3 并且 可以被二整除 的元素，  
25. a[0 , 0:2]//取 0 到 2 的值，但不包括2 ( 左闭右开)  
a[0 , :] 和 a[0] 语法都没有错误  
26. a[ 0 : 9 : 2] ：取 下标 0 到 9 的值（左闭右开） ，且 跨度等于2  
当跨度为负值时，可以从右向左逆向遍历这个数组。  
如 a[::-1] : 将数组反转了一下  
27. np.shape : 将返回 三个参数 行 ， 列 ， 分量数量  

# 数组的创建

rerzer's note：  
.size  
.shape  
.reshape()  
.zeros((3,2)) #创建一个三行两列的全为0的矩阵 
.ones(()) #创建一个元素全为1的矩阵  
.fill((x,y,z),n) #创建一个m维元素全是n的矩阵  
.eyes(n) #创建一个n维单位阵  
.arange() #类似与range（）是一个左闭右开区间，即取前不取后；np.arange()与Python中的range（）不同的是，np的步长可以是浮点数，而range只能是整数  
.linspase(a,b,n) #[a,b)区间等分成n份，每份的值存储在数组内  
.random.rand((x,y,z))#创建一个随机数组，其取值范围为[0.0,1.0)  
.randim.randn(x,y,z) #同上，区别是可以取到负数,且不需要加括号了  
.random.randint（a,b,size=(x,y,z)）
.random.normal(u,r,n) #u是均值，r是标准差，n是生成个数  
.dtype #查看数据类型，在数组生成时也可以指定数组的类型，即dtype=np.int64  
.astype() #转换数组的数据类型  



# 数组的计算

两个相同尺寸的数组可以直接进行四则运算，即加减乘除，会将数组同位置的元素进行加减乘除（两个列表用“+”号产生的效果是拼接，而不是像np一样对应相同位置进行相加）  
np.dot() #将两个**向量**进行点乘运算，np.dot(A,B)  
@ #是将两个矩阵是**矩阵**的乘法运算,A@B  
实则上述两个是一样的效果，均可以对矩阵和向量进行点乘运算  
np.sqrt(A) #矩阵中的每个元素的算术平方根 -square root  
np.log(A) #每个元素$a_{ij}$对数运算，默认是以e为第，要更改，则np.log2;np.log10()  
np.power(A,n) #指数运算$n^{a_{ij}}$  
### 广播机制
A*5


# 关于筛选特定数据

[Python有关运算符](https://www.cnblogs.com/shouhu/p/11727582.html)  
补充一下上述网址没包含位运算符，即& | ~   
两个布尔数组进行 & 运算时，会进行逐位比较，并返回一个新的布尔数组。对于每一对位置上的布尔值，& 运算符将按以下规则计算  
* True&True==>True
* False&True==>False
* True&False==>False
* False&False==>False  
"a<n"会返回一个**索引掩码**，[True,True,False,False,True],然后索引掩码再带入a中，即a[np.array([True,True,False,False,True])],则只返回为True的对应位置的元素，即返回含三个元素的数组[a[0],a[1],a[4]];直接用列表也可以，即a[[True,True,False,False,True]]  
numpy通过位运算符组合不同的条件，&是按位与运算符，用来在两个布尔数组之间进行逐位比较，最终得到一个新的布尔数组。  
a=np.arange(10)  
(a < 8) & (a > 3) 会对 a < 8 和 a > 3 的结果逐位进行 "**与**" 运算，返回一个新的布尔数组。  
(a < 8)  # [True, True, True, True, True, True, True, True, False, False] ---(1)  
(a > 3)  # [False, False, False, False, True, True, True, True, True, True ---(2)  
(1)式和(2)式通过逐位进行"与"逻辑运算，得出一个新的波尔数组，逐位是指(1)式的第$i$和(2)式的第$i$位进行**与**逻辑操作  
[False, False, False, False, True, True, True, True, False, False]  
mask=(a<8>)&(a>3)  
a[mask] #返回的是一个满足条件值，形状为一维数组  
np.where(mask,a,0) #返回的是跟原数组相同形状的矩阵，where函数的第一个参数是筛选条件（即该参数输入索引掩码），第二个参数是从哪里筛选，第三个参数是在False（即不满足条件）的位置显示指定内容，也可以是np.nan  
np.argwhere(mask) #返回满足条件的索引，若$a_{ij}$满足条件，则会以数组形式返回其下标[i,j]  




In [2]:
import numpy as np
a=np.arange(10)
# a[(a<8) & (a>3)]
a=np.arange(2,4)
# a[np.array([True,False])]
#a[[True,False]]

In [3]:

a=np.random.rand(3,2)
b=np.random.rand(2,3)
c=np.dot(a,b)
print(c,'\n',b@a)

[[0.25938809 0.11779146 0.20096578]
 [0.76628965 0.62455744 0.64591378]
 [0.92662523 0.67889443 0.76664904]] 
 [[0.55818117 0.79234849]
 [0.61219962 1.0924134 ]]


In [4]:
a=np.random.rand(3,2,2)
a,a.sum(axis=0)

(array([[[0.77535949, 0.15272434],
         [0.040122  , 0.32231975]],
 
        [[0.87326234, 0.73716773],
         [0.82036641, 0.04867193]],
 
        [[0.37827619, 0.94217239],
         [0.4228359 , 0.69900271]]]),
 array([[2.02689802, 1.83206446],
        [1.28332431, 1.06999439]]))

## 关于切片
* 关于切片 -slice（索引，筛选），其标准样式为a[x:y:n]（一维），由两个引号分离开形成三个空间，第一个空间为起始位置，第二个空间为结束位置,第三个空间为步长;二维则是a[x1:y1:n1,x2:y2:n2]和维度的看法是一样的，即第一位是最高维，由高维向低维排列；
* Python的切片是按照其索引位置进行切片的，索引是一定的，是不会改变的，是从0开始的
* Python的切片一般都是取前不取后（步长为正），即[a,b)前闭后开的区间，其在步长为一的情况下，总共的元素个数为(b-a), 若步长大于1则含有的个数为[(b-a)/n],其中a为初始点，b为终点，n为步长，[]是取整符号 --[x]是指不超过x的最大整数；当步长为负的时候则是指，从最后一个数往前取数，取还是可以沿用步长为正的思路，例如：a[4:2:-1]是指从索引为4的那个数的位置开始根据步长为1往前取数，同样也是取前不取后，即取a[4],a[3]这两数，不取a[2];取数的个数为$[\frac{|(a-b)|}{n}]$,其发生变化的是将（a-b）添加了绝对值
* 关于对切片的解读a[a:b],解读为从a开始到(b-1)结束
* 指定某些行与某些列的切片方法a[[1,3,4],[4,5,8]]
* 假如我们想slicing第n行到第m行，则我们检索的写法为a[n,m+1],(m+1)-n 是我们能得到的真是行数;逆向来说我们需要从第n列开始到结束一共k列，其取法为a[n,n+(k+1)]
* 关于索引掩码[快速抵达](https://www.bilibili.com/video/BV1xK411X7ZQ?t=844.4)
* "a<n"会返回一个索引掩码，[True,True,False,False,True],然后索引掩码再带入a中，即a[np.array([True,True,False,False,True])],则只返回为True的对应位置的元素，即返回含三个元素的数组[a[0],a[1],a[4]]  

In [5]:
text=np.arange(100).reshape(10,10)
text[[1,3,7],[1,3,7]]


array([11, 33, 77])

# 有关于维度的解释

有关于矩阵的维度的相关解释：  
* 关于维度的看法是：从最后一位向前看 ，列，行，层... 
* axis = 0，axis = 1...；其中0,1,2,3...n；0是指形状的第一个元素，相当于将形状看成一个序列（从零开始计数），axis=n就是序列的索引，是指（$D_1,D_2,D_3,...,D_i$）中的第n个元素，例如：对于一个四维矩阵(2,4,3,5)，2对应着最高维四维（由两个三维矩阵构成）axis=0，是指第一个元素也就是第四维，axis=2是指第二维，同理axis=3是指第一维
* （1,2,2,1,4,5） 这个维度看起来是六维矩阵，但是其中的“1”维度可以省去，即该维度视为四维矩阵
* 其中一维维度有五个元素，即一个一维有五个元素；二维维度有四个元素，即一个二维矩阵由四个一维矩阵构成；三维维度有两个元素，即一个三维矩阵由两个二维矩阵构成；一个四维维度有两个元素，即一个四维矩阵由两个三维矩阵构成；
* 一维由n个元素构成，二维由n个一维构成，三维由n个二维构成，n维由n-1维构成,即3D=2D+2D+2D+...+2D;4D=3D+3D+3D+...+3D;
* 最高维的个数永远是一，即四维矩阵的最高维是四维，且只有一个四维矩阵，其他维度矩阵的个数可以是任意的

* 对矩阵的二维进行聚类函数等函数操作，其作用的的矩阵的当前维度-1的矩阵，如对一维进行.max（）,[1,2,3,4,5,6,7,8,9].max() ==>[9],其作用的矩阵就是单个元素，即每个元素进行比较求出max；同理对二维矩阵进行函数操作，其作用的矩阵是2-1维的矩阵，即每个一位进行max比较，最后返回的结果就是一个一维数组；对三维进行函数操作，即各个二维矩阵间进行比较，最后返回的结果是一个二维数组，即 MAX 3D =MAX[2D 2D 2D ... 2D] ==>2D,即MAX 3D ==> 2D，对三维求max会返回一个二维的结果;MAX 4D=MAX[3D 3D 3D ...3D] ==> 3D，对四维求MAX返回一个三维结果；

* 还有就是对四维矩阵np.random.rand(2,4,3,5)的三维进行.max(axis=1)，按照上一条的规律总结，对三维进行MAX之后其作用的3-1维矩阵，也就是二维矩阵，MAX 3D==> 2D,即返回一个二维矩阵；又因为4D = [3D 3D 3D ...3D];[3D 3D 3D ...3D]==>[2D 2D 2D ... 2D];故4D = [2D 2D 2D ... 2D] ，即4D由多个2D构成，但是也可反正看，由多个2D构成的矩阵是3D，故此时4D降维成3D,3D降维成2D，即对n维进行函数操作之后，n维和比n维更高的维的维度都-1；还可以换一种角度看，就是对于四维(2,4,3,5)中的三维进行降维打击即四维(2,4,3,5)==>(2,1,3,5)==>(2,3,5),即一维二维的元素个数不变，三维的个数变为一
* 比如关于对三维求.max（axis=1）的作用机理，如果对于一个四维矩阵np.random.rand(2,4,3,5)对三维进行.max(axis=1)，其作用的是二维矩阵，即每个三维矩阵中的n个二维进行比较然后返回最大值的二维矩阵，这样每个三维矩阵是由一个二维矩阵构成，那么一个四维（最高维）所包裹的m个三维就变成了四维包裹的m个二维，由m个二维所构成的是三维，即此时四维转变为三维，原因是原有的三维的元素个数被降为一个相当于(2,4,3,5)~~>(2,1,3,5)==>(2,3,5)
**矩阵最高维为N，则矩阵其实是由n个N-1维的矩阵构成，如果我们想让m维度之间进行比较，则需要再原索引值-1，如在上述例子中，要比较各个三维之间的值，则需要输入三维高一维的四维的索引值就行，因为4D=3D+3D+3D+...+3D;MAX 4D=MAX[3D 3D 3D ...3D] ==>3D**

In [6]:
import numpy as np
a = np.random.rand(3,4,3,5,6)
a

array([[[[[0.52709218, 0.74474852, 0.37532386, 0.19468024, 0.52793096,
           0.38693126],
          [0.25184394, 0.25250765, 0.45116932, 0.39700546, 0.25306027,
           0.4967883 ],
          [0.57230719, 0.45734474, 0.80851729, 0.6155573 , 0.14445827,
           0.72304965],
          [0.89214081, 0.56216629, 0.00774609, 0.47217591, 0.7885928 ,
           0.74997431],
          [0.34370073, 0.02992819, 0.34820647, 0.25881633, 0.08316831,
           0.54830385]],

         [[0.24770889, 0.88539433, 0.44065068, 0.98132965, 0.5448054 ,
           0.99303414],
          [0.08317007, 0.21229809, 0.5543552 , 0.94895947, 0.38880212,
           0.73179531],
          [0.31036015, 0.77287676, 0.18224751, 0.31055074, 0.92163615,
           0.7929907 ],
          [0.98920095, 0.49104159, 0.50014764, 0.21770724, 0.65723888,
           0.49238023],
          [0.26945263, 0.90845594, 0.1027384 , 0.15689295, 0.37100671,
           0.30941567]],

         [[0.84135698, 0.03947619, 0.30569727,

In [7]:
a=list(range(10))
a,a[3:1:-1]


([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [3, 2])

# 深拷贝与浅拷贝


a.view() #浅拷贝

In [13]:
#text1.view()相当于一下的效果
text1=np.arange(10)

text2=text1
text2[0]=99

text_view=text1.view()
text_view[0]=88

print(text1)
print(text2)
print(text_view)

[88  1  2  3  4  5  6  7  8  9]
[88  1  2  3  4  5  6  7  8  9]
[88  1  2  3  4  5  6  7  8  9]


a.copy() #深拷贝，其效果是上个cell的text2更新值后，不会影响text1，copy之后text1和text2是两个独立互不影响的矩阵，所以修改任何一个对象都不会影响另一个对象

In [12]:
#text1.copy()相当于一下的效果
text1=np.arange(10)

text2=text1
text2[0]=99

text_copy=text1.copy()
text_copy[0]=88

print(text1)
print(text2)
print(text_copy)

[99  1  2  3  4  5  6  7  8  9]
[99  1  2  3  4  5  6  7  8  9]
[88  1  2  3  4  5  6  7  8  9]


# 字符串类型的数据 string

np.unique(a) #去重  
np.concatenate(a,b) #a左连接b，直接拼接，即列表list_1 + list_2最终形成的结果   
np.insert(a,k,b) #在a的索引为k的位置插入b，a[k:]的位置整体后移，最终形成的元素集为[a[:k]+b+a[k:]],即$[n_0,n_1,n_2,...,b,n_k,n_{k+1},...,n_{end}]$  
np.delete(a,n) #删除索引为k的元素